In [66]:
import numpy as np
import quadpy
from plind.contour_dict import equilateral_real

In [82]:
dim = 2
scheme = quadpy.nsimplex.grundmann_moeller(dim, 3)

simps = np.stack([ 
        [[0.0, 0.0],
        [0.0, 1.0],
        [1.0, 0.0]],
    
        [[1.0, 1.0],
        [0.0, 1.0],
        [1.0, 0.0]]
        ], axis=-2)

val = scheme.integrate(
    lambda x: x[0]*x[0]+x[1]*x[1],
    simps
    )

In [83]:
simps.shape

(3, 2, 2)

In [68]:
sum(val)

0.6666666666666663

In [69]:
def transform(points, simplex):
    """Transform the points `xi` from the reference simplex onto `simplex`.
    """
    # For n == 2:
    # x = (
    #     + outer(triangle[0].T, 1.0 - xi[0] - xi[1])
    #     + outer(triangle[1].T, xi[0])
    #     + outer(triangle[2].T, xi[1])
    #     )
    return numpy.dot(simplex, points)

In [70]:
scheme = quadpy.nsimplex.grundmann_moeller(dim, 3)

f = lambda x: x[0]
simplex = np.array([[0.0, 0.0],
        [0.0, 1.0],
        [1.0, 0.0]]) 

flt = numpy.vectorize(float)
simplex = numpy.asarray(simplex)
x = transform(flt(scheme.points).T, simplex.T)

fx = numpy.asarray(f(x))

In [71]:
x[0]

array([0.11111111, 0.11111111, 0.33333333, 0.11111111, 0.33333333,
       0.55555556, 0.11111111, 0.33333333, 0.55555556, 0.77777778,
       0.14285714, 0.14285714, 0.42857143, 0.14285714, 0.42857143,
       0.71428571, 0.2       , 0.2       , 0.6       , 0.33333333])

In [72]:
np.dot(simplex.T, flt(scheme.points).T)

array([[0.11111111, 0.11111111, 0.33333333, 0.11111111, 0.33333333,
        0.55555556, 0.11111111, 0.33333333, 0.55555556, 0.77777778,
        0.14285714, 0.14285714, 0.42857143, 0.14285714, 0.42857143,
        0.71428571, 0.2       , 0.2       , 0.6       , 0.33333333],
       [0.11111111, 0.33333333, 0.11111111, 0.55555556, 0.33333333,
        0.11111111, 0.77777778, 0.55555556, 0.33333333, 0.11111111,
        0.14285714, 0.42857143, 0.14285714, 0.71428571, 0.42857143,
        0.14285714, 0.2       , 0.6       , 0.2       , 0.33333333]])

In [73]:
simplex.T

array([[0., 0., 1.],
       [0., 1., 0.]])

In [86]:
contour = equilateral_real(20, (-0.5,0.5,-0.5,0.5))

In [87]:
contour.simplices

array([[  0,   1,  20],
       [ 20,  21,   1],
       [  1,   2,  21],
       ...,
       [397, 398, 378],
       [378, 379, 398],
       [398, 399, 379]])

In [88]:
simps = contour.points[contour.simplices]

In [91]:
simps = np.stack(simps, axis=-2)

In [92]:
val = scheme.integrate(
    lambda x: x[0]/x[0],
    simps
    )

In [94]:
sum(val)

0.9999999999999918

In [95]:
contour.ndim

2