In [8]:
import numpy as np
import quadpy

In [58]:
dim = 2
scheme = quadpy.nsimplex.grundmann_moeller(dim, 3)

simps = np.stack([ 
        [[0.0, 0.0],
        [0.0, 1.0],
        [1.0, 0.0]],
    
        [[1.0, 1.0],
        [0.0, 1.0],
        [1.0, 0.0]]
        ], axis=-2)

val = scheme.integrate(
    lambda x: x[0]*x[0]+xp1[,
    simps
    )

In [59]:
val

array([0.60350798, 0.60350798])

In [37]:
def transform(points, simplex):
    """Transform the points `xi` from the reference simplex onto `simplex`.
    """
    # For n == 2:
    # x = (
    #     + outer(triangle[0].T, 1.0 - xi[0] - xi[1])
    #     + outer(triangle[1].T, xi[0])
    #     + outer(triangle[2].T, xi[1])
    #     )
    return numpy.dot(simplex, points)

In [42]:
scheme = quadpy.nsimplex.grundmann_moeller(dim, 3)

f = lambda x: x[0]
simplex = np.array([[0.0, 0.0],
        [0.0, 1.0],
        [1.0, 0.0]]) 

flt = numpy.vectorize(float)
simplex = numpy.asarray(simplex)
x = transform(flt(scheme.points).T, simplex.T)

fx = numpy.asarray(f(x))

In [53]:
x[0]

array([0.11111111, 0.11111111, 0.33333333, 0.11111111, 0.33333333,
       0.55555556, 0.11111111, 0.33333333, 0.55555556, 0.77777778,
       0.14285714, 0.14285714, 0.42857143, 0.14285714, 0.42857143,
       0.71428571, 0.2       , 0.2       , 0.6       , 0.33333333])

In [49]:
np.dot(simplex.T, flt(scheme.points).T)

array([[0.11111111, 0.11111111, 0.33333333, 0.11111111, 0.33333333,
        0.55555556, 0.11111111, 0.33333333, 0.55555556, 0.77777778,
        0.14285714, 0.14285714, 0.42857143, 0.14285714, 0.42857143,
        0.71428571, 0.2       , 0.2       , 0.6       , 0.33333333],
       [0.11111111, 0.33333333, 0.11111111, 0.55555556, 0.33333333,
        0.11111111, 0.77777778, 0.55555556, 0.33333333, 0.11111111,
        0.14285714, 0.42857143, 0.14285714, 0.71428571, 0.42857143,
        0.14285714, 0.2       , 0.6       , 0.2       , 0.33333333]])

In [52]:
simplex.T

array([[0., 0., 1.],
       [0., 1., 0.]])