In [4]:
import numpy as np
import quadpy
from plind.contour_dict import equilateral_real

In [82]:
dim = 2
scheme = quadpy.nsimplex.grundmann_moeller(dim, 3)

simps = np.stack([ 
        [[0.0, 0.0],
        [0.0, 1.0],
        [1.0, 0.0]],
    
        [[1.0, 1.0],
        [0.0, 1.0],
        [1.0, 0.0]]
        ], axis=-2)

val = scheme.integrate(
    lambda x: x[0]*x[0]+x[1]*x[1],
    simps
    )

In [83]:
simps.shape

(3, 2, 2)

In [68]:
sum(val)

0.6666666666666663

In [69]:
def transform(points, simplex):
    """Transform the points `xi` from the reference simplex onto `simplex`.
    """
    # For n == 2:
    # x = (
    #     + outer(triangle[0].T, 1.0 - xi[0] - xi[1])
    #     + outer(triangle[1].T, xi[0])
    #     + outer(triangle[2].T, xi[1])
    #     )
    return numpy.dot(simplex, points)

In [70]:
scheme = quadpy.nsimplex.grundmann_moeller(dim, 3)

f = lambda x: x[0]
simplex = np.array([[0.0, 0.0],
        [0.0, 1.0],
        [1.0, 0.0]]) 

flt = numpy.vectorize(float)
simplex = numpy.asarray(simplex)
x = transform(flt(scheme.points).T, simplex.T)

fx = numpy.asarray(f(x))

In [71]:
x[0]

array([0.11111111, 0.11111111, 0.33333333, 0.11111111, 0.33333333,
       0.55555556, 0.11111111, 0.33333333, 0.55555556, 0.77777778,
       0.14285714, 0.14285714, 0.42857143, 0.14285714, 0.42857143,
       0.71428571, 0.2       , 0.2       , 0.6       , 0.33333333])

In [72]:
np.dot(simplex.T, flt(scheme.points).T)

array([[0.11111111, 0.11111111, 0.33333333, 0.11111111, 0.33333333,
        0.55555556, 0.11111111, 0.33333333, 0.55555556, 0.77777778,
        0.14285714, 0.14285714, 0.42857143, 0.14285714, 0.42857143,
        0.71428571, 0.2       , 0.2       , 0.6       , 0.33333333],
       [0.11111111, 0.33333333, 0.11111111, 0.55555556, 0.33333333,
        0.11111111, 0.77777778, 0.55555556, 0.33333333, 0.11111111,
        0.14285714, 0.42857143, 0.14285714, 0.71428571, 0.42857143,
        0.14285714, 0.2       , 0.6       , 0.2       , 0.33333333]])

In [73]:
simplex.T

array([[0., 0., 1.],
       [0., 1., 0.]])

In [86]:
contour = equilateral_real(20, (-0.5,0.5,-0.5,0.5))

In [87]:
contour.simplices

array([[  0,   1,  20],
       [ 20,  21,   1],
       [  1,   2,  21],
       ...,
       [397, 398, 378],
       [378, 379, 398],
       [398, 399, 379]])

In [88]:
simps = contour.points[contour.simplices]

In [91]:
simps = np.stack(simps, axis=-2)

In [92]:
val = scheme.integrate(
    lambda x: x[0]/x[0],
    simps
    )

In [94]:
sum(val)

0.9999999999999918

In [95]:
contour.ndim

2

# Playing with numba

In [623]:
from numba import jit

@jit(nopython=True)
def isin_nb(simplices, edge, invert=False):
    isin_arr = [False]
    for i in np.arange(simplices.shape[0]):
        simp = simplices[i]
        for a in simp:
            bool_val = False
            for e in edge:
                if a == e:
                    bool_val = True
            isin_arr.append(bool_val)

    isin_arr = np.array(isin_arr[1:])
    isin_arr = isin_arr.reshape(simplices.shape)
    if invert:
        return np.invert(isin_arr)
    else:
        return isin_arr

def split_edges(points, edges, simplices, ndim, bad_edges, indicies):
    used_simps = np.array([], dtype=np.int)
    uni_bad_edges = np.array([], dtype=np.int)
    uni_bad_simps = np.array([], dtype=np.int)

    # The surface becomes inconsistent if two edges within the same simplex are flagged at once.
    # To combat this, only the first edge is split, and the second is assumed to be caught
    # by the subsequent time step
    for i in np.arange(bad_edges.shape[0]):
        bad_edge = bad_edges[i]
        # Keep track of the simplices associated with an edge
        isin_arr = isin_nb(simplices, bad_edge)
        simplices_tag = np.array(isin_arr).sum(axis=-1) > 1
        # simplices_tag = np.isin(simplices, bad_edge).sum(axis=-1) > 1

        simplices_tag = np.where(simplices_tag)[0]

        if not np.any(np.in1d(simplices_tag, used_simps)):  # Check if we have used this simplex
            # Flag simplices_tag to not reuse simplices
            used_simps = np.append(used_simps, simplices_tag)
            # Add edge to new bad edge array
            uni_bad_edges = np.append(uni_bad_edges, bad_edge)
            # Remove bad edges from the list of edges
            edges_tag = isin_nb(edges, bad_edge).sum(axis=-1) == 2
            edges = edges[~(edges_tag)]

            # Add simplice(s) with the proper extras populated
            for j in range(ndim):
                if np.size(simplices_tag) > j:
                    uni_bad_simps = np.append(uni_bad_simps, simplices[simplices_tag[j]], axis=0)

    # The only edges this function treats and removes are uni_bad_edges,
    # that is, the edges that are unique with respect to their simplices.
    uni_bad_simps = uni_bad_simps.reshape(-1, ndim+1)
    uni_bad_edges = uni_bad_edges.reshape(-1, 2)

    # Add the midpoints of all the bad edges
    midpts_ind = np.arange(np.shape(points)[0], np.shape(points)[0]+np.shape(uni_bad_edges)[0], 1, dtype=np.int)
    midpts = (points[uni_bad_edges[:, 0]] + points[uni_bad_edges[:, 1]])/2
    points = np.append(points, midpts, axis=0)

    # Add the two edges that replace all the bad edges
    edges_1 = np.sort(np.append(midpts_ind, uni_bad_edges[:, 0], axis=0).reshape(2,-1).T, axis=1)
    edges_2 = np.sort(np.append(midpts_ind, uni_bad_edges[:, 1], axis=0).reshape(2,-1).T, axis=1)
    edges = np.concatenate((edges, edges_1, edges_2), axis=0)

    # Delete all the bad edges
    simplices = np.delete(simplices, used_simps, axis=0)

    # vertices which are not part of the bad edges in the bad simplices
    for i, bad_edge in enumerate(uni_bad_edges):
            # Get all points in the simplex not associated to the edge ("outliers")


            outliers = uni_bad_simps[isin_nb(uni_bad_simps, bad_edge, invert=True) *
                        (isin_nb(uni_bad_simps, bad_edge, invert=True).sum(axis=-1)==ndim+1-2)[:, np.newaxis]]
            # ndim - 1 outliers will exist in every edge
            if ndim == 1:
                num_simps = 1
            else:
                num_simps = int(np.size(outliers)/(ndim-1))
            num_outliers=np.size(outliers)
            outliers=np.reshape(outliers,[num_outliers,1])

            # add new edge for every outlier
            edges_outliers = np.sort(np.append(outliers, midpts_ind[i]*np.ones([num_outliers, 1], dtype=np.int),axis=1), axis=0)
            edges_outliers = edges_outliers.astype(np.int)
            edges = np.append(edges, edges_outliers, axis=0)
            outliers = np.reshape(outliers, [num_simps, ndim-1])

            # Simplices per outlier row
            simp_1 = np.sort(np.concatenate(( midpts_ind[i]*np.ones([num_simps, 1], dtype=np.int),outliers,bad_edge[0]*np.ones([num_simps, 1], dtype=np.int)),axis=1), axis=1)
            simp_2 = np.sort(np.concatenate(( midpts_ind[i]*np.ones([num_simps, 1], dtype=np.int),outliers,bad_edge[1]*np.ones([num_simps, 1], dtype=np.int)),axis=1), axis=1)

            simplices = np.concatenate((simplices, simp_1, simp_2), axis=0)
    return points, edges, simplices

@jit(nopython=True)
def sum_nb(isin_arr):
    summed = np.zeros(isin_arr.shape[0], dtype=np.int64)
    for i in np.arange(0, isin_arr.shape[1]):
        summed[i] = np.sum(isin_arr[i])
    return summed

@jit(nopython=True)
def in1d_nb(arr0, arr1):
    out_arr = np.zeros(len(arr0), np.bool_)
    for i in np.arange(0, len(arr0)):
        for j in np.arange(0, len(arr1)):
            if arr0[i] == arr1[j]:
                out_arr[i] = True
    return out_arr

@jit(nopython=True)
def delete_row_nb(arr, num):
    mask = np.zeros(arr.shape[0], dtype=np.int64) == 0
    mask[num] = False
    return arr[mask]

@jit(nopython=True)
def rowarr_transpose_nb(rowarr):
    colarr = np.zeros((len(rowarr), 1), rowarr.dtype)
    for i in np.arange(0, len(rowarr)):
        colarr[i, 0] = rowarr[i]
    return colarr

@jit(nopython=True)
def bool_index_nb(arr, bool_arr):
    out = np.zeros(np.sum(bool_arr.flatten()), arr.dtype)
    j = 0
    for i in np.arange(0, bool_arr.size):
        if bool_arr.flatten()[i]:
            out[j] = arr.flatten()[i]
            j += 1
    return out
    
@jit(nopython=True)
def split_edges_nb(points, edges, simplices, ndim, bad_edges, indicies):
    used_simps = np.zeros(1, np.int64) - 1
    uni_bad_edges = np.zeros((1,2), np.int64) 
    uni_bad_simps = np.zeros((1,ndim+1), np.int64)

    # The surface becomes inconsistent if two edges within the same simplex are flagged at once.
    # To combat this, only the first edge is split, and the second is assumed to be caught
    # by the subsequent time step
    for i in np.arange(bad_edges.shape[0]):
        bad_edge = bad_edges[i]
        # Keep track of the simplices associated with an edge
        simplices_tag = np.where(sum_nb(isin_nb(simplices, bad_edge))>1)[0]

        if not np.any(in1d_nb(simplices_tag, used_simps)):  # Check if we have used this simplex
            # Flag simplices_tag to not reuse simplices
            if i == 0:
                used_simps = simplices_tag
            else:
                used_simps = np.concatenate((used_simps, simplices_tag))
            # Add edge to new bad edge array
            if i == 0:
                uni_bad_edges[0] = bad_edge
            else:
                uni_bad_edges = np.concatenate((uni_bad_edges.ravel(), bad_edge)).reshape((uni_bad_edges.shape[0]+1,2))
            # Remove bad edges from the list of edges
            edges_tag = sum_nb(isin_nb(edges, bad_edge)) == 2
            edges = edges[~(edges_tag)]

            # Add simplice(s) with the proper extras populated
            for j in range(ndim):
                if simplices_tag.size > j:
                    uni_bad_simps = np.concatenate((uni_bad_simps.ravel(), simplices[simplices_tag[j]])).reshape((uni_bad_simps.shape[0]+1, uni_bad_simps.shape[1]))

    # The only edges this function treats and removes are uni_bad_edges,
    # that is, the edges that are unique with respect to their simplices.
    uni_bad_simps = uni_bad_simps.reshape(-1, ndim+1)
    uni_bad_edges = uni_bad_edges.reshape(-1, 2)

    # Add the midpoints of all the bad edges
    midpts_ind = np.arange(points.shape[0], points.shape[0] + uni_bad_edges.shape[0], 1)
    midpts = (points[uni_bad_edges[:, 0]] + points[uni_bad_edges[:, 1]])/2
    points = np.concatenate((points.ravel(), midpts.ravel())).reshape(len(points)+len(midpts),ndim)

#     # Add the two edges that replace all the bad edges
    edges_1 = np.concatenate((midpts_ind, uni_bad_edges[:, 0])).reshape(2,-1).T
    edges_2 = np.concatenate((midpts_ind, uni_bad_edges[:, 1])).reshape(2,-1).T
    edges = np.concatenate((edges, edges_1, edges_2), axis=0)

#     # Delete all the bad edges
    for ind in used_simps:
        simplices = delete_row_nb(simplices, ind)
     
    
    # vertices which are not part of the bad edges in the bad simplices
    for i in np.arange(0, len(uni_bad_edges)):
        # Get all points in the simplex not associated to the edge ("outliers")
        bad_edge = uni_bad_edges[i]

        outliers = bool_index_nb(uni_bad_simps, isin_nb(uni_bad_simps, bad_edge, invert=True) * 
        rowarr_transpose_nb(sum_nb(isin_nb(uni_bad_simps, bad_edge, invert=True))==ndim+1-2))

        # ndim - 1 outliers will exist in every edge
        num_outliers = outliers.size
        if ndim == 1:
            num_simps = 1
        else:
            num_simps = int(num_outliers/(ndim-1))
        outliers_T = outliers.reshape(num_outliers,1)

        # add new edge for every outlier
        edges_outliers = np.concatenate((outliers_T, midpts_ind[i]*np.ones((num_outliers, 1), dtype=np.int64)), axis=1)
        edges = np.concatenate((edges, edges_outliers), axis=0)
        outliers_S = outliers_T.reshape(num_simps, ndim-1)

        # Simplices per outlier row
        simp_1 = np.concatenate(( midpts_ind[i]*np.ones((num_simps, 1), dtype=np.int64), outliers_S, bad_edge[0]*np.ones((num_simps, 1), dtype=np.int64)),axis=1)
        simp_2 = np.concatenate(( midpts_ind[i]*np.ones((num_simps, 1), dtype=np.int64),outliers_S, bad_edge[1]*np.ones((num_simps, 1), dtype=np.int64)),axis=1)

        simplices = np.concatenate((simplices, simp_1, simp_2), axis=0)
    return points, edges, simplices

In [624]:
points = np.array([[0.,0.],[0.,1.],[1.,1.],[1.,0.]])
edges = np.array([[0,1],[1,2],[2,3],[3,0],[0,2]])
simplices = np.array([[0,1,2],[2,3,0]])
ndim = 2
bad_edges = np.array([[0,2]])
indices = np.array([4])

points0, edges0, simplices0 = split_edges_nb(points, edges, simplices, ndim, bad_edges, indices)

In [610]:
points = np.array([[0.,0.],[0.,1.],[1.,1.],[1.,0.]])
edges = np.array([[0,1],[1,2],[2,3],[3,0],[0,2]])
simplices = np.array([[0,1,2],[2,3,0]])
ndim = 2
bad_edges = np.array([[0,2]])
indices = np.array([4])

points1, edges1, simplices1 = split_edges(points, edges, simplices, ndim, bad_edges, indices)

In [630]:
simplices0

array([[2, 3, 0],
       [4, 1, 0],
       [4, 3, 0],
       [4, 1, 2],
       [4, 3, 2]])

In [629]:
simplices1

array([[0, 1, 4],
       [0, 3, 4],
       [1, 2, 4],
       [2, 3, 4]])

In [444]:
used_simps = np.zeros(1, np.int64) - 1
uni_bad_edges = np.zeros((1,2), np.int64) - 1
uni_bad_simps = np.zeros((1,ndim+1), np.int64) - 1

# The surface becomes inconsistent if two edges within the same simplex are flagged at once.
# To combat this, only the first edge is split, and the second is assumed to be caught
# by the subsequent time step
for i in np.arange(bad_edges.shape[0]):
    bad_edge = bad_edges[i]
    # Keep track of the simplices associated with an edge
    simplices_tag = np.where(sum_nb(isin_nb(simplices, bad_edge))>1)[0]


    if not np.any(in1d_nb(simplices_tag, used_simps)):  # Check if we have used this simplex
        # Flag simplices_tag to not reuse simplices
        used_simps = np.concatenate((used_simps, simplices_tag))
        # Add edge to new bad edge array
        uni_bad_edges = np.concatenate((uni_bad_edges.ravel(), bad_edge)).reshape((uni_bad_edges.shape[0]+1,2))
        # Remove bad edges from the list of edges
        edges_tag = sum_nb(isin_nb(edges, bad_edge)) == 2
        edges = edges[~(edges_tag)]

        # Add simplice(s) with the proper extras populated
        for j in range(ndim):
            if simplices_tag.size > j:
                uni_bad_simps = np.concatenate((uni_bad_simps.ravel(), simplices[simplices_tag[j]])).reshape((uni_bad_simps.shape[0]+1, uni_bad_simps.shape[1]))

# The only edges this function treats and removes are uni_bad_edges,
# that is, the edges that are unique with respect to their simplices.
uni_bad_simps = uni_bad_simps.reshape(-1, ndim+1)
uni_bad_edges = uni_bad_edges.reshape(-1, 2)

# Add the midpoints of all the bad edges
midpts_ind = np.arange(points.shape[0], points.shape[0] + uni_bad_edges.shape[0], 1)
midpts = (points[uni_bad_edges[:, 0]] + points[uni_bad_edges[:, 1]])/2
points = np.concatenate((points.ravel(), midpts.ravel())).reshape(len(points)+len(midpts),ndim)

#     # Add the two edges that replace all the bad edges
edges_1 = np.concatenate((midpts_ind, uni_bad_edges[:, 0])).reshape(2,-1).T
edges_2 = np.concatenate((midpts_ind, uni_bad_edges[:, 1])).reshape(2,-1).T
edges = np.concatenate((edges, edges_1, edges_2), axis=0)

#     # Delete all the bad edges
for ind in used_simps:
    simplices = delete_row_nb(simplices, ind)


# vertices which are not part of the bad edges in the bad simplices
for i in np.arange(0, len(uni_bad_edges)):
    # Get all points in the simplex not associated to the edge ("outliers")
    bad_edge = uni_bad_edges[i]

    outliers = bool_index_nb(uni_bad_simps, isin_nb(uni_bad_simps, bad_edge, invert=True) * 
        rowarr_transpose_nb(sum_nb(isin_nb(uni_bad_simps, bad_edge, invert=True))==ndim+1-2))
    
    num_outliers = outliers.size
    if ndim == 1:
        num_simps = 1
    else:
        num_simps = int(num_outliers/(ndim-1))
    outliers_T =np.reshape(outliers,[num_outliers,1])
    
    edges_outliers = np.sort(np.append(outliers_T, midpts_ind[i]*np.ones([num_outliers, 1], dtype=np.int64),axis=1), axis=0)

In [449]:
np.append(outliers_T, midpts_ind[i]*np.ones([num_outliers, 1], dtype=np.int64),axis=1)

array([[1, 5],
       [3, 5]])

In [455]:
np.concatenate((outliers_T, midpts_ind[i]*np.ones([num_outliers, 1], dtype=np.int64)), axis=1)

array([[1, 5],
       [3, 5]])

In [452]:
np.concatenate((outliers, ))

array([[5],
       [5]])

In [454]:
midpts_ind[i]*np.ones(num_outliers, dtype=np.int64)

array([5, 5])

In [615]:
@jit(nopython=True)
def empty():
    a = np.empty(1, np.int64)
    return np.concatenate((a,np.array([5])))

In [616]:
empty()

array([-3761688987579986997,                    5])